### ISSUE TITLE
Having trouble doing "save" requests

### ISSUE THREAD

**Issue by riyazshaikh** [NodeSquarespace/node-squarespace-middleware#13]
I was hoping to use this node-squarespace-middleware as a programmatic way to add posts/code/tweaks/anything to a squarespace site. Unfortunately, I'm getting "Access denied: Invalid session crumb" errors when I try to do something like this:

```javascript
sqsMiddleware.doLogin(function ( error, headers ) {
  request({
    		method: "POST",
    		json: true,
    		headers: headers,
    		form: { /* obj of code injection settings */ },
    		url: sqsMiddleware.get('siteurl') + "/api/config/SaveInjectionSettings"
    	}, function(e, response, json) {
    		console.log('saved', e, json, headers);
    	});
});
```

Have you tried doing anything like this? Thanks!

**Comment by riyazshaikh** [comment]
Managed to figure this out... you need to pass crumb as a qs param. This is great!

**Comment by kitajchuk** [comment]
@riyazshaikh - I've never played with this endpoint before. Can you elaborate at all on its capabilities? - sounds really fun :)

**Comment by webbexpert** [comment]
Where did you source the crumb from? I'm having the same trouble, but cannot seem to find where the crumb is stored

Disregard: Its in the cookie collection
